### ISSUE TITLE
Have you try to implement CoDA into ResNet series or VGG like common archtectures?

### ISSUE THREAD

**Issue by TyroneLi** [moboehle/CoDA-Nets#1]
As mentioned above.

**Comment by moboehle** [comment]
Hi @TyroneLi, sorry for the late reply, I did not notice this issue was opened. To answer your question, I would like to point you to our work on the B-cos Networks (CVPR 2022). In this work, we use a similar approach to design interpretable networks, but make sure that it remains easily compatible with standard architectures. I hope this answers your question!
